version: '3.8'
services:
  database:
    image: postgres:latest
    env_file: ./.env
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
