version: '3.8'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - 3000:3000
    depends_on:
      - database
    
  database:
    image: postgres:latest
    env_file: ./.env
    ports:
      - 5432:5432
