version: '3.8'
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    
  database:
    image: postgres:latest
    env_file: ./.env
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:${POSTGRES_PORT}"
  
volumes:
  database:
    
